global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
# - "first_rules.yml"
# - "second_rules.yml"

scrape_configs:
  # LDAP-to-ID Proxy metrics
  - job_name: "ldaptoid"
    static_configs:
      - targets: ["ldaptoid:9090"]
    metrics_path: "/metrics"
    scrape_interval: 15s
    scrape_timeout: 10s

  # Redis metrics
  - job_name: "redis"
    static_configs:
      - targets: ["redis-exporter:9121"]
    scrape_interval: 15s

  # Prometheus self-monitoring
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  # Health checks for all services
  - job_name: "ldaptoid-health"
    static_configs:
      - targets: ["ldaptoid:8080"]
    metrics_path: "/health"
    scrape_interval: 30s
    scrape_timeout: 5s
